- hosts: all
  tasks:
  - name: update packages
    become: yes
    apt:
      name: "*"
      state: latest
  - name: enable camera
    become: yes
    copy:
      src: config.txt
      dest: /boot/config.txt
      backup: no
      owner: root
      group: root
      mode: 0755
    register: bootconfig
    tags:
      - camera
  - name: reboot the system when boot config changes
    shell: 'sleep 1 && shutdown -r now "Reboot triggered by Ansible" && sleep 1'
    async: 1
    poll: 0
    become: yes
    when: bootconfig.changed
    register: rebooting
    tags:
      - camera
  - name: waiting for server to come back
    local_action: wait_for host={{ ansible_default_ipv4.address }} port=22 state=started delay=30 timeout=60
    when: rebooting.changed
    tags:
      - camera
  - name: enable /dev/video0
    become: yes
    modprobe:
      name: bcm2835-v4l2
      state: present
    tags:
      - camera
  - name: bcm2835-v4l2 on boot
    become: yes
    copy:
      src: bcm2835-v4l2.conf
      dest: /etc/modules-load.d/bcm2835-v4l2.conf
      backup: no
      owner: root
      group: root
      mode: 0755
    tags:
      - camera
  - name: enable en_US.UTF-8
    become: yes
    replace:
      path: /etc/locale.gen
      regexp: '^# en_US.UTF-8'
      replace: 'en_US.UTF-8'
      backup: yes
    register: locale
    tags:
      - locale
  - name: generate locale
    become: yes
    command: locale-gen
    when: locale.changed
    tags:
      - locale
  - name: disable swap (required by kubelet)
    become: yes
    systemd:
      name: dphys-swapfile
      state: stopped
      enabled: no
    tags:
      - swap
  - name: check if docker is installed
    command: dpkg -s docker-ce
    register: docker_check
    ignore_errors: True
    tags:
      - docker
  - name: download docker install helper
    get_url:
      url: https://get.docker.com
      dest: /tmp/getdocker.sh
      mode: 0755
    tags:
      - docker
    when: docker_check is failed
  - name: install docker
    become: yes
    shell: /tmp/getdocker.sh
    tags:
      - docker
    when: docker_check is failed
  - name: add {{ ansible_user }} to docker and video group
    become: yes
    user:
      name: "{{ ansible_user }}"
      groups: docker,video
      append: yes
    tags:
      - docker
